### ISSUE TITLE
Authenticating with scope

### ISSUE THREAD

**Issue by why-not-try-calmer** [lakinwecker/lichess-oauth-flask#1]
`return oauth.lichess.authorize_redirect(redirect_uri)`

is fine when there is no scope, but the point of authenticating with OAuth is often to make requests required some scope. Also, the Node JS example for authenticating from Node features scopes. 

Thus may I humbly suggest at least a comment of the form:

`return oauth.lichess.authorize_redirect(redirect_uri, scope=...)    # fill the dots with the scopes you require as per https://lichess.org/api#section/Authentication ` 

The authlib OAuth object is quite complex and it's not always obvious where the scope should be passed.

**Comment by lakinwecker** [comment]
Dunno when I'll get to it, but will try to find time. I'd happily review a PR right away though.

**Comment by why-not-try-calmer** [comment]
> Dunno when I'll get to it, but will try to find time. I'd happily review a PR right away though.

#2

**Comment by lakinwecker** [comment]
Thanks!

**Comment by lepture** [comment]
Checkout https://docs.authlib.org/en/latest/client/frameworks.html#using-oauth-2-0-to-log-in
`scope` is in `client_kwargs`.

We have an example of Google login at https://github.com/authlib/demo-oauth-client/blob/master/flask-google-login/app.py
